import './globals.css'
import type { Metadata } from 'next'
import { Epilogue, Inter } from 'next/font/google'

const epilogue = Epilogue({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Intro section',
  description: 'Generated by create next app, coded by Abdelilah',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={epilogue.className}>{children}</body>
    </html>
  )
}
